config/routes.rb
Rails.application.routes.draw do
  resources :tokens
  resources :applications do
    resources :preceptions, only: [:create]
    resources :problems, only: [:create, :update]
  end

  get 'patients' => 'patients#index'
  get 'medicines' => 'medicines#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

  authenticated :user do
    root :to => 'active_tokens#index', as: :authenticated_root
  end
  root :to => 'welcome#index'

  resources :users
  resources :roles

end

app/models/application.rb
class Application < ActiveRecord::Base
	has_many :tokens
	has_many :preceptions
	has_many :problems

  	validates_presence_of :name
  	validates_presence_of :relation_name

	#Problem = ["Head", "Hair", "Eye", "Ear", "Nose", "Ear", "Fever", "Cold", "Stomach", "Hand", "Leg"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :authenticate_user!

	rescue_from CanCan::AccessDenied do |exception|
		flash[:error] = "Access denied!. You Don't have access to do this action."
		redirect_to root_url
	end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all.page(params[:page]).per(10)
  end

  # GET /applications/1
  # GET /applications/1.json
  def show

    # @application = Application.find(params[:id])
    # @lastToken = @application.tokens ? @application.tokens.last : []
    # @lastFiveTokens = @application.tokens.last(5)
    # @allTokens = @application.tokens

      @problems = @application.problems.reverse_each
      @prescriptions = @application.preceptions ? @application.preceptions.order("created_at desc") : [] 

  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :relation_name, :address, :details, :is_doctor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= f.label :name %>: </b><span class="input_madatory">*</span><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <b><%= f.label :relation_name %>: </b><span class="input_madatory">*</span><br>
    <%= f.text_field :relation_name %>
  </div>
  <div class="field">
    <b><%= f.label :address %>: </b><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <b><%= f.label :details %>: </b><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <b><%= f.label :is_doctor %>: </b>
    <%= f.check_box :is_doctor %><br>
  </div>
  <div><b>Note: </b> All<span class="input_madatory">*</span>&nbsp; marks are madatory to fill</div><br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<!-- <p id="notice"><%# notice %></p> -->

<h1>Applications</h1>
<div class="create-form-link">
  <%= link_to 'New Application', new_application_path %>
</div>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Relation name</th>
      <th>Address</th>
      <th>Details</th>
      <!-- <th>Is doctor</th> -->
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.id %></td>
        <td><%= application.name %></td>
        <td><%= application.relation_name %></td>
        <td><%= application.address %></td>
        <td><%= application.details %></td>
        <!-- <td><%# application.is_doctor %></td> -->
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <!-- <td><%# link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination_wrapper">
  <%= paginate @applications %>
</div>

<br>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Application No:</strong>
  <%= @application.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @application.name %>
</p>

<p>
  <strong>Relation name:</strong>
  <%= @application.relation_name %>
</p>

<p>
  <strong>Is doctor:</strong>
  <%= @application.is_doctor %>
</p>

<p>
  <strong>Address:</strong>
  <%= @application.address %>
</p>

<p>
  <strong>Problems: </strong>
  <%# @application.details %>
</p>

<% if @problems %>
  <ol style="border:1px solid orange; border-radius: 5px; padding: 20px;margin: 10px;list-style-type:none;  ">
    <% @problems.each do |problem| %>
    <li>
      <div style="width:55%;float: left;">
        <b>Entered By: </b> <i><%= problem.entered_by %></i>
      </div>
      <div style="width:45%;float: left;text-align: right;">
      <b>Identifed on: </b> <i><%= problem.updated_at.strftime("%dth %b %Y at %I:%M %p") %></i>
    </div>
    <div>
        <b>Problem: </b> <%= problem.problem_type %>
        <% if problem.other_problem_type && problem.other_problem_type != '' %><span>(<%= problem.other_problem_type %>)</span>
        <% end %>
    </div>
    <div>
      <b>Description: </b><%= problem.description %>
    </div>
    </li>  
    <hr/>

    <% end %>  
  </ol>
<% end %>

<%# if [2,5,8].include?(current_user.role_id) %>
<div>
  <h3>Create Problem: </h3>
  <div style="border:1px solid orange; border-radius: 5px; padding: 20px;margin: 10px;">
    <%= form_for([@application, @application.problems.build]) do |f| %>

      <div>
        <div><b>Problem Type: </b> <span class="input_madatory">*</span></div>
        <%# f.text_field :problem_type %>
        <%= f.collection_select :problem_type, Problem::TYPE, :to_s, :to_s, :include_blank => true %>
      </div>
      <div id="problem_other_problem_type_container" >
        <div><b>Other Problem Type: </b> <span class="input_madatory">*</span> </div>
        <%= f.text_field :other_problem_type, rows: 3, cols: 40 %>
      </div><br/>
      <div>
        <div><b>Description: </b> <span class="input_madatory">*</span> </div>
        <%= f.text_area :description, rows: 3, cols: 40 %>
      </div><br/>
      <div><b>Note: </b> All<span class="input_madatory">*</span>&nbsp; marks are madatory to fill</div><br/>
      <div>
        <%= f.submit "Create Problem" %>
      </div>
    <% end %>
  </div>
</div>
<%# end %>

<h3>Prescriptions: </h3>

<% if @application.preceptions %>
  <div style="border:1px solid orange; border-radius: 5px; padding: 20px;margin: 10px;">
    <% @prescriptions.each do |preception| %>

    <div style="width:55%;float:left;">
      <b>Doctor Name: </b> <%= preception.doctor_name %>
    </div>
    <div style="width:45%;float: left;text-align: right;">
      <b>Visited on: </b> <i><%= preception.updated_at.strftime("%dth %b %Y at %I:%M %p") %></i>
    </div>
    <div>
      <b>Problem: </b><%= preception.problem %>
    </div>
    <div>
      <b>Medicine: </b><%= preception.medicine %>
    </div>
    <hr/>

    <% end %>  
  </div>
<% end %>
<% if [2,5,8].include?(current_user.role_id) %>
  <div>
    <h3>Create Prescription: </h3>
    <div style="border:1px solid orange; border-radius: 5px; padding: 20px;margin: 10px;">
      <%= form_for([@application, @application.preceptions.build]) do |f| %>

        <!-- <div>
          <div><b>Doctor Name: </b> <span class="input_madatory">*</span> </div>
          <%# f.text_field :doctor_name %>
        </div><br/> -->

        <div>
          <div><b>Problem: </b> <span class="input_madatory">*</span> </div>
          <%= f.text_area :problem, rows: 3, cols: 40 %>
        </div><br/>

        <div>
          <div><b>Medicine: </b> <span class="input_madatory">*</span> </div>
          <%= f.text_area :medicine, rows: 9, cols: 40 %>
        </div><br/>
        <div><b>Note: </b> All<span class="input_madatory">*</span>&nbsp; marks are madatory to fill</div><br/>
        <div>
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<br/>

<hr/>
<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>
<%# @lastToken %>

<%# if @lastToken %>
<!-- <div>
  <p>Last Token</p>
  <%# @lastToken.each do | lastToken | %>
    <div>Last Token Id: <%# lastToken.id %></div>
    <div>Last Token Date: <%# lastToken.updated_at %></div>
  <%# end %>
</div> -->
<%# end %>

<%# if @lastFiveTokens %>
<!-- <div>
  <p>Last Five Tokens</p>
  <%# @lastFiveTokens %>
</div> -->
<%# end %>

<%# if @allTokens %>
<!-- <div>
  <p>Last Token</p>
  <%# @allTokens %>
</div> -->
<%# end %>