config/routes.rb
Rails.application.routes.draw do
  resources :tokens
  resources :applications do
    resources :preceptions, only: [:create]
    resources :problems, only: [:create, :update]
  end

  get 'patients' => 'patients#index'
  get 'medicines' => 'medicines#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

  authenticated :user do
    root :to => 'active_tokens#index', as: :authenticated_root
  end
  root :to => 'welcome#index'

  resources :users
  resources :roles

end

app/models/token.rb
class Token < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :relation_name
	validates :application_id, inclusion: { in: Application.all.map{|a| a.id},
    message: "%{value} is not a valid Application Number" }, :unless => :is_new_application?
  belongs_to :application
  DOCTORS = User.where("role_id IN (?)", [2,5,8]).collect{|d| d.name}
  USERS = User.all.collect{|d| d.name}
  STATUS = ["Started", "Waited for Checkup", "Waited for Medicine", "Medicine given", "Closed"]
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_filter :authenticate_user!
  #before_action :set_token, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all.page(params[:page]).per(10)
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    #@token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens
  # POST /tokens.json
  def create
    #@token = Token.new(token_params)
    if(@token.is_new_application)
      @new_application = Application.new(:name => @token.name, :relation_name => @token.relation_name);
      @new_application.save!
      @token.application_id = @new_application.id
    end
     
    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, notice: 'Token was successfully created.' }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_url, notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_token
    #   @token = Token.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
      params.require(:token).permit(:name, :relation_name, :doctor, :is_new_application, :application_id, :is_active, :staff1, :staff2, :is_staff2_involved, :status)
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_form.html.erb
<%= form_for @token, :html => {:class => 'form-horizontal', :role=>"form"} do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <b><%= f.label :name %> : </b><span class="input_madatory">*</span><br/>
    <%= f.text_field :name %>
  </div>
  <div class="form-group field">
    <b><%= f.label :is_active %> : </b>
    <%= f.check_box :is_active, :id => "idIsActive" %>
  </div>
  <div class="form-group field">
    <b><label for="doctor">Doctor Name: </label></b><br/>
    <%= f.collection_select :doctor, Token::DOCTORS, :to_s, :to_s, :include_blank => true %>
  </div>
  <div class="form-group field">
    <b><%= f.label :relation_name %> : </b><span class="input_madatory">*</span><br/>
    <%= f.text_field :relation_name %>
  </div>
  <div class="form-group field">
    <b><%= f.label :is_new_application %> : </b><span id="is_new_application_error"  class="input_madatory">*</span>
    <%= f.check_box :is_new_application, :id => "idIsNewApplication" %>
  </div>
  <div class="form-group field">
    <b><%= f.label :application_id %> : </b><span id="application_id_error" class="input_madatory">*</span><br/>
    <%= f.text_field :application_id if @token.new_record? %>
    <%= f.text_field :application_id,:readonly => true unless @token.new_record?%>
  </div>
  <div class="form-group field">
    <b><label for="staff1">Medicine prepared by </label> : </b> <br/>
    <%= f.collection_select :staff1, Token::USERS, :to_s, :to_s, :include_blank => true %><br/>    
  </div>
   <div class="form-group field" style="display:none;">
    <label for="is_staff2">Second Person Invoved in Medicine Prepare: </label>
    <%= f.check_box :is_staff2_involved%>
   </div>
  <div class="form-group field" id="token_staff2_container" style="display:none;">
    <b><label for="staff2">Medicine prepared by </label> : </b><span id="application_id_error" class="input_madatory">*</span><br/>
    <%= f.collection_select :staff2, Token::USERS, :to_s, :to_s, :include_blank => true %>
  </div>
  <div class="form-group field">
    <b><label for="status">Token Status </label> : </b><br/>
    <%= f.collection_select :status, Token::STATUS, :to_s, :to_s %>
  </div>
  <div><b>Note: </b> All<span class="input_madatory">*</span>&nbsp; marks are madatory to fill. <br/>
  Application No is mandatory if patient is previous patient else click on is_new_application checkbox for new patient</div><br/>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<!-- <p id="notice"><%# notice %></p> -->

<h1>Tokens</h1>
<% if can? :create, Token %>
  <div class="create-form-link">
    <%= link_to 'New Token', new_token_path %>
  </div>
<% end %>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Relation Name</th>
      <th>Doctor Name</th>
      <th>Application Id</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.id %></td>
        <td><%= token.name %></td>
        <td><%= token.relation_name %></td>
        <td><%= token.doctor %></td>
        <td><%= link_to token.application_id, application_path(token.application_id) %></td>
        <td><%= link_to 'Show', token %></td>
        <td>
          <% if can? :update, Token %>
            <%= link_to 'Edit', edit_token_path(token) %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, Token %>
            <%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination_wrapper">
  <%= paginate @tokens %>
</div>

<br>

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<!-- <p id="notice"><%# notice %></p> -->

<p>
  <strong>Name:</strong>
  <%= @token.name %>
</p>

<p>
  <strong>Relation name:</strong>
  <%= @token.relation_name %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @token.doctor %>
</p>

<p>
  <strong>Is Active:</strong>
  <%= @token.is_active %>
</p>

<p>
  <strong>Is new application:</strong>
  <%= @token.is_new_application %>
</p>

<p>
  <strong>Application id:</strong>
  <%= @token.application.id %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>