config/routes.rb
Rails.application.routes.draw do
  resources :tokens
  resources :applications do
    resources :preceptions, only: [:create]
    resources :problems, only: [:create, :update]
  end

  get 'patients' => 'patients#index'
  get 'medicines' => 'medicines#index'

  devise_for :users
  scope "/admin" do
    resources :users
  end

  authenticated :user do
    root :to => 'active_tokens#index', as: :authenticated_root
  end
  root :to => 'welcome#index'

  resources :users
  resources :roles

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>HomeoHospital</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <!-- Latest compiled and minified CSS -->
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		Optional theme
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> -->
		
	</head>
	<body>
	<div class="container">
		<h1 class="main-heading">Welcome to Navanetha Evergreens Homeo Hospital</h1>
		<div class="nav-header">

			<% if user_signed_in? %>
			  Signed in as <%= current_user.email %>.
			   <!-- Not you? -->
			  <%# link_to "Edit profile", edit_user_registration_path %>
			  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			<% else %>
			  <%# link_to "Sign up", new_user_registration_path %> <%= link_to "sign in", new_user_session_path %>
			<% end %>
		</div>
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, id: "flash_#{name}" %>
		<% end %>
		

		<% if user_signed_in? %>
			<nav>
				<ul>
					<li style="list-style-type: none; display: inline-block;" click="linkClick()"><%= link_to 'Home', root_path, :style => "padding: 8px;", :click => 'javascript:linkClick()' %></li>
					<li style="list-style-type: none; display: inline-block;" click="linkClick()"><%= link_to 'Tokens', tokens_path, :style => "padding: 8px;" %></li>
					<% if [2,5,8].include?(current_user.role_id) %>
					<li style="list-style-type: none; display: inline-block;" click="linkClick()"><%= link_to 'Patients', patients_path, :style => "padding: 8px;" %></li>
					<% end %>
					<li style="list-style-type: none; display: inline-block;" click="linkClick()"><%= link_to 'Medicines', medicines_path, :style => "padding: 8px;" %></li>
					<li style="list-style-type: none; display: inline-block;" click="linkClick()"><%= link_to 'Applications', applications_path, :style => "padding: 8px;" %></li>
				</ul>
			</nav>
		<% end %>

		<%= yield %>
		<!-- Latest compiled and minified JavaScript -->
		<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>-->
		</div>
	</body>
</html>